name: Java CI with Gradle

on:
  push:
    paths:
      - '**.java'
      - '**.json'
      - 'gradle**'
      - 'build.gradle'
  pull_request:
    paths:
      - '**.java'
      - '**.json'
      - 'gradle**'
      - 'build.gradle'
  # Makes it possible to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
        build-scan-terms-of-use-agree: "yes"

    - name: Generate and submit dependency graph
      if: ${{ github.event_name == 'push' }}
      uses: gradle/actions/dependency-submission@v4

    - name: Run tests and build
      run: ./gradlew build --stacktrace --warning-mode=fail

    - name: VirusTotal scan
      if: ${{ github.event_name == 'push' }}
      uses: crazy-max/ghaction-virustotal@v4
      with:
        vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        files: |
          ./build/libs/*.jar
      continue-on-error: true

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Wurst
        path: build/libs/

    - name: Read data from gradle.properties
      id: read_properties
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: './gradle.properties'
        properties: 'minecraft_version mod_version'

    - name: Trim whitespace from mod version
      run: echo "MOD_VERSION=$(echo ${{ steps.read_properties.outputs.mod_version }} | tr -d '[:space:]')" >> $GITHUB_ENV

    - name: Release
      uses: "ThisTestUser/marvinpinto-action-automatic-releases@1.0"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ steps.read_properties.outputs.minecraft_version }}"
        prerelease: false
        title: "Wurst Client - ThisTestUser's Edition for ${{ steps.read_properties.outputs.minecraft_version }}"
        files: |
          build/libs/Wurst-Client-${{ env.MOD_VERSION }}.jar
