name: "Compile and Publish"

on: [push]

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Read data from gradle.properties
        id: read_properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'minecraft_version mod_version'

      - name: Trim whitespace from mod version
        run: echo "MOD_VERSION=$(echo ${{ steps.read_properties.outputs.mod_version }} | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wurst
          path: build/libs/

      - name: Release
        uses: "ThisTestUser/marvinpinto-action-automatic-releases@1.0"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.read_properties.outputs.minecraft_version }}"
          prerelease: false
          title: "Wurst Client - ThisTestUser's Edition for ${{ steps.read_properties.outputs.minecraft_version }}"
          files: |
            build/libs/Wurst-Client-${{ env.MOD_VERSION }}.jar
